* irace/target-runner: Modernize.

diff --git a/irace/target-runner b/irace/target-runner
--- a/irace/target-runner
+++ b/irace/target-runner
@@ -2,28 +2,25 @@
 ###############################################################################
 # This script is to tune the ACOTSPQAP software.
 #
+# This script is run in the execution directory (execDir, --exec-dir).
+#
 # PARAMETERS:
-# $1 is the ID of the candidate to be evaluated
+# $1 is the candidate configuration number
 # $2 is the instance ID
 # $3 is the seed
 # $4 is the instance name
-# The rest ($* after `shift 4') are parameters for running ACOTSP
+# The rest ($* after `shift 4') are parameters to the run
 #
 # RETURN VALUE:
-# This script should print a single numerical value (the value to be minimized).
+# This script should print one numerical value: the cost that must be minimized.
+# Exit with 0 if no error, with 1 in case of error
 ###############################################################################
 error() {
-    echo "`TZ=UTC date`: $0: error: $@" >&2
+    echo "`TZ=UTC date`: $0: error: $@"
     exit 1
 }
 
-# Path to the ACOTSP software:
-EXE=~/bin/acotsp
-
-# Fixed parameters that should be always passed to ACOTSP.
-# The time to be used is always 5 seconds, and we want only one run:
-FIXED_PARAMS=" --time 60 --tries 1 --quiet "
-
+# This parses the arguments given by irace. Do not touch it!
 CONFIG_ID="$1"
 INSTANCE_ID="$2"
 SEED="$3"
@@ -31,19 +28,26 @@ INSTANCE="$4"
 # All other parameters are the candidate parameters to be passed to program
 shift 4 || error "Not enough parameters to $0"
 CONFIG_PARAMS=$*
+# End of parsing
+
+## Find our own location.
+# BINDIR=$(dirname "$(readlink -f "$(type -P $0 || echo $0)")")
+
+# EDIT THIS: Path to the ACOTSP/ACOQAP software:
+EXE=~/bin/acoqap
+# EDIT THIS: Specify how parameters are given to your executable
+EXE_PARAMS="--time 60 --tries 1 --quiet -i $INSTANCE --seed $SEED ${CONFIG_PARAMS}"
+
+if [ ! -x "$(command -v ${EXE})" ]; then
+    error "${EXE}: not found or not executable (pwd: $(pwd))"
+fi
 
 STDOUT=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stdout
 STDERR=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stderr
 
-if [ ! -x "${EXE}" ]; then
-    error "${EXE}: not found or not executable (pwd: $(pwd))"
-fi
-
 # Now we can call ACOTSP by building a command line with all parameters for it
-$EXE ${FIXED_PARAMS} -i $INSTANCE --seed $SEED ${CONFIG_PARAMS} 1> $STDOUT 2> $STDERR
+$EXE ${EXE_PARAMS}  1> $STDOUT 2> $STDERR
 
-# The output of the candidate $CONFIG_ID should be written in the file 
-# c${CONFIG_ID}.stdout (see target runner for ACOTSP).
 # Does this file exist?
 if [ ! -s "${STDOUT}" ]; then
     # In this case, the file does not exist. Let's exit with a value 
